version: "3.9"

services:
  web:
    build: .
    container_name: flask_app
    expose:
      - "8000"

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
